const bogus = {
  abfdefghijklmnopqrstuvwxyzABFDEFGHIJKLMNOPQRSTUVWXYZabfdefghijklmnopqrstuvwxyz: 'ABFDEFGHIJKLMNOPQRSTUVWXYZ',
  abfdefghijklmnopqrstuvwxyz: 'ABFDEFGHIJKLMNOPQRSTUVWXYZabfdefghijklmnopqrstuvwxyzABFDEFGHIJKLMNOPQRSTUVWXYZ',
}
